### ISSUE TITLE
Double full image

### ISSUE THREAD

**Issue by Christian69229** [BytewaveMLP/randibooru#2]
For some reason now the default derpibooru.org links now show the full picture, leaving that with 2 full pictures, it needs to be fixed so it only shows 1 picture. (The file below is an example just for you to know what I mean)

![ss 2017-01-15 at 08 55 38](https://cloud.githubusercontent.com/assets/25138121/21965678/27369ef8-db65-11e6-9aef-c5700286cf0f.jpg)

**Comment by BytewaveMLP** [comment]
It appears Discord changed the appearance of embedded images.

I'll submit a patch that should remove the "Full image" link. That should fix it.

**Comment by BytewaveMLP** [comment]
At some point I'd like to use the Embeds API, but discord.py doesn't really seem to support it without using the undocumented Bot style. I'd migrate if it was documented, but yknow.

**Comment by BytewaveMLP** [comment]
Fixed. Will update my hosted version soon.

**Comment by BytewaveMLP** [comment]
Updated. Thanks for the report!
